# Form implementation generated from reading ui file 'c:\Users\Student\Documents\Author Regis\Avtoriz.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Avtorization(object):
    def setupUi(self, Avtorization):
        Avtorization.setObjectName("Avtorization")
        Avtorization.resize(297, 300)
        self.login_text = QtWidgets.QLineEdit(parent=Avtorization)
        self.login_text.setGeometry(QtCore.QRect(30, 30, 241, 31))
        self.login_text.setObjectName("login_text")
        self.password_text = QtWidgets.QLineEdit(parent=Avtorization)
        self.password_text.setGeometry(QtCore.QRect(30, 90, 241, 31))
        self.password_text.setText("")
        self.password_text.setObjectName("password_text")
        self.enterBtn = QtWidgets.QPushButton(parent=Avtorization)
        self.enterBtn.setGeometry(QtCore.QRect(80, 190, 121, 31))
        self.enterBtn.setObjectName("enterBtn")
        self.regBtn = QtWidgets.QPushButton(parent=Avtorization)
        self.regBtn.setGeometry(QtCore.QRect(80, 240, 121, 31))
        self.regBtn.setObjectName("regBtn")

        self.retranslateUi(Avtorization)
        QtCore.QMetaObject.connectSlotsByName(Avtorization)

    def retranslateUi(self, Avtorization):
        _translate = QtCore.QCoreApplication.translate
        Avtorization.setWindowTitle(_translate("Avtorization", "Form"))
        self.login_text.setPlaceholderText(_translate("Avtorization", "Логин"))
        self.password_text.setPlaceholderText(_translate("Avtorization", "Пароль"))
        self.enterBtn.setText(_translate("Avtorization", "Вход"))
        self.regBtn.setText(_translate("Avtorization", "Регистрация"))
