# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Avtoriz.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Avtorization(object):
    def setupUi(self, Avtorization):
        Avtorization.setObjectName("Avtorization")
        Avtorization.resize(394, 497)
        Avtorization.setStyleSheet("QObject  {\n"
"    \n"
"    font: 63 11pt \"Yu Gothic UI Semibold\";\n"
"    background-color: rgb(255, 240, 247);\n"
"}\n"
"QPushButton {\n"
"background-color: rgb(214, 196, 202);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"   \n"
"    background-color: rgb(100, 102, 115);\n"
"    border-style: inset;\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"    selection-background-color: darkgray;\n"
"}\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    lineedit-password-character: 9679;\n"
"}\n"
"")
        self.login_text = QtWidgets.QLineEdit(Avtorization)
        self.login_text.setGeometry(QtCore.QRect(70, 80, 261, 31))
        self.login_text.setObjectName("login_text")
        self.password_text = QtWidgets.QLineEdit(Avtorization)
        self.password_text.setGeometry(QtCore.QRect(70, 140, 261, 31))
        self.password_text.setText("")
        self.password_text.setObjectName("password_text")
        self.enterBtn = QtWidgets.QPushButton(Avtorization)
        self.enterBtn.setGeometry(QtCore.QRect(90, 360, 221, 31))
        self.enterBtn.setObjectName("enterBtn")
        self.regBtn = QtWidgets.QPushButton(Avtorization)
        self.regBtn.setGeometry(QtCore.QRect(90, 410, 221, 31))
        self.regBtn.setObjectName("regBtn")

        self.retranslateUi(Avtorization)
        QtCore.QMetaObject.connectSlotsByName(Avtorization)

    def retranslateUi(self, Avtorization):
        _translate = QtCore.QCoreApplication.translate
        Avtorization.setWindowTitle(_translate("Avtorization", "Авторизация"))
        self.login_text.setPlaceholderText(_translate("Avtorization", "Логин"))
        self.password_text.setPlaceholderText(_translate("Avtorization", "Пароль"))
        self.enterBtn.setText(_translate("Avtorization", "Вход"))
        self.regBtn.setText(_translate("Avtorization", "Регистрация"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Avtorization = QtWidgets.QWidget()
    ui = Ui_Avtorization()
    ui.setupUi(Avtorization)
    Avtorization.show()
    sys.exit(app.exec_())
