# Form implementation generated from reading ui file 'c:\Users\Student\Documents\Author Regis\Regis.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(283, 355)
        self.name_text = QtWidgets.QLineEdit(parent=Registration)
        self.name_text.setGeometry(QtCore.QRect(30, 20, 221, 31))
        self.name_text.setText("")
        self.name_text.setObjectName("name_text")
        self.lastname_next = QtWidgets.QLineEdit(parent=Registration)
        self.lastname_next.setGeometry(QtCore.QRect(30, 70, 221, 31))
        self.lastname_next.setObjectName("lastname_next")
        self.login_textReg = QtWidgets.QLineEdit(parent=Registration)
        self.login_textReg.setGeometry(QtCore.QRect(30, 120, 221, 31))
        self.login_textReg.setObjectName("login_textReg")
        self.password_textReg = QtWidgets.QLineEdit(parent=Registration)
        self.password_textReg.setGeometry(QtCore.QRect(30, 170, 221, 31))
        self.password_textReg.setObjectName("password_textReg")
        self.zaregBtn = QtWidgets.QPushButton(parent=Registration)
        self.zaregBtn.setGeometry(QtCore.QRect(60, 260, 161, 31))
        self.zaregBtn.setObjectName("zaregBtn")
        self.cancelBtn = QtWidgets.QPushButton(parent=Registration)
        self.cancelBtn.setGeometry(QtCore.QRect(60, 300, 161, 31))
        self.cancelBtn.setObjectName("cancelBtn")

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Form"))
        self.name_text.setPlaceholderText(_translate("Registration", "Имя"))
        self.lastname_next.setPlaceholderText(_translate("Registration", "Фамилия"))
        self.login_textReg.setPlaceholderText(_translate("Registration", "Логин"))
        self.password_textReg.setPlaceholderText(_translate("Registration", "Пароль"))
        self.zaregBtn.setText(_translate("Registration", "Зарегистрироваться"))
        self.cancelBtn.setText(_translate("Registration", "Отмена"))
