# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Regis.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Registration(object):
    def setupUi(self, Registration):
        Registration.setObjectName("Registration")
        Registration.resize(381, 509)
        Registration.setStyleSheet("QObject  {\n"
"    \n"
"    font: 63 11pt \"Yu Gothic UI Semibold\";\n"
"    background-color: rgb(255, 240, 247);\n"
"}\n"
"QPushButton {\n"
"background-color: rgb(214, 196, 202);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"   \n"
"    background-color: rgb(100, 102, 115);\n"
"    border-style: inset;\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"    selection-background-color: darkgray;\n"
"}\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    lineedit-password-character: 9679;\n"
"}\n"
"")
        self.lastname_next = QtWidgets.QLineEdit(Registration)
        self.lastname_next.setGeometry(QtCore.QRect(60, 90, 261, 31))
        self.lastname_next.setObjectName("lastname_next")
        self.login_textReg = QtWidgets.QLineEdit(Registration)
        self.login_textReg.setGeometry(QtCore.QRect(60, 140, 261, 31))
        self.login_textReg.setObjectName("login_textReg")
        self.password_textReg = QtWidgets.QLineEdit(Registration)
        self.password_textReg.setGeometry(QtCore.QRect(60, 190, 261, 31))
        self.password_textReg.setObjectName("password_textReg")
        self.zaregBtn = QtWidgets.QPushButton(Registration)
        self.zaregBtn.setGeometry(QtCore.QRect(90, 360, 206, 31))
        self.zaregBtn.setObjectName("zaregBtn")
        self.cancelBtn = QtWidgets.QPushButton(Registration)
        self.cancelBtn.setGeometry(QtCore.QRect(90, 410, 206, 31))
        self.cancelBtn.setObjectName("cancelBtn")
        self.name_text = QtWidgets.QLineEdit(Registration)
        self.name_text.setGeometry(QtCore.QRect(60, 40, 261, 31))
        self.name_text.setText("")
        self.name_text.setObjectName("name_text")

        self.retranslateUi(Registration)
        QtCore.QMetaObject.connectSlotsByName(Registration)

    def retranslateUi(self, Registration):
        _translate = QtCore.QCoreApplication.translate
        Registration.setWindowTitle(_translate("Registration", "Регистрация"))
        self.lastname_next.setPlaceholderText(_translate("Registration", "Фамилия"))
        self.login_textReg.setPlaceholderText(_translate("Registration", "Логин"))
        self.password_textReg.setPlaceholderText(_translate("Registration", "Пароль"))
        self.zaregBtn.setText(_translate("Registration", "Зарегистрироваться"))
        self.cancelBtn.setText(_translate("Registration", "Отмена"))
        self.name_text.setPlaceholderText(_translate("Registration", "Имя"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Registration = QtWidgets.QWidget()
    ui = Ui_Registration()
    ui.setupUi(Registration)
    Registration.show()
    sys.exit(app.exec_())
