# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WrongW.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WrongWindow(object):
    def setupUi(self, WrongWindow):
        WrongWindow.setObjectName("WrongWindow")
        WrongWindow.resize(370, 153)
        WrongWindow.setStyleSheet("QObject  {\n"
"    \n"
"    font: 63 11pt \"Yu Gothic UI Semibold\";\n"
"    background-color: rgb(255, 240, 247);\n"
"}\n"
"QPushButton {\n"
"background-color: rgb(214, 196, 202);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"   \n"
"    background-color: rgb(100, 102, 115);\n"
"    border-style: inset;\n"
"}\n"
"")
        self.wrong_label = QtWidgets.QLabel(WrongWindow)
        self.wrong_label.setGeometry(QtCore.QRect(80, 30, 261, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(11)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(7)
        self.wrong_label.setFont(font)
        self.wrong_label.setObjectName("wrong_label")
        self.okBtn = QtWidgets.QPushButton(WrongWindow)
        self.okBtn.setGeometry(QtCore.QRect(80, 100, 206, 31))
        self.okBtn.setObjectName("okBtn")

        self.retranslateUi(WrongWindow)
        QtCore.QMetaObject.connectSlotsByName(WrongWindow)

    def retranslateUi(self, WrongWindow):
        _translate = QtCore.QCoreApplication.translate
        WrongWindow.setWindowTitle(_translate("WrongWindow", "Внимание!"))
        self.wrong_label.setText(_translate("WrongWindow", "Вы успешно зарегистрировались"))
        self.okBtn.setText(_translate("WrongWindow", "Ок"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WrongWindow = QtWidgets.QWidget()
    ui = Ui_WrongWindow()
    ui.setupUi(WrongWindow)
    WrongWindow.show()
    sys.exit(app.exec_())
