# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sd.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(316, 569)
        Form.setStyleSheet("background-color: rgb(255, 226, 227);")
        self.input_shirina = QtWidgets.QLineEdit(Form)
        self.input_shirina.setGeometry(QtCore.QRect(60, 130, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.input_shirina.setFont(font)
        self.input_shirina.setStyleSheet("color: rgb(85, 85, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.input_shirina.setObjectName("input_shirina")
        self.input_vusota = QtWidgets.QLineEdit(Form)
        self.input_vusota.setGeometry(QtCore.QRect(60, 180, 201, 20))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.input_vusota.setFont(font)
        self.input_vusota.setStyleSheet("color: rgb(85, 85, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.input_vusota.setObjectName("input_vusota")
        self.checkBoxx3 = QtWidgets.QCheckBox(Form)
        self.checkBoxx3.setGeometry(QtCore.QRect(80, 230, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.checkBoxx3.setFont(font)
        self.checkBoxx3.setStyleSheet("color: rgb(85, 85, 127);")
        self.checkBoxx3.setObjectName("checkBoxx3")
        self.checkBoxPlus100 = QtWidgets.QCheckBox(Form)
        self.checkBoxPlus100.setGeometry(QtCore.QRect(80, 260, 121, 17))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.checkBoxPlus100.setFont(font)
        self.checkBoxPlus100.setStyleSheet("color: rgb(85, 85, 127);")
        self.checkBoxPlus100.setObjectName("checkBoxPlus100")
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setGeometry(QtCore.QRect(80, 290, 131, 17))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setStyleSheet("color: rgb(85, 85, 127);")
        self.checkBox_2.setObjectName("checkBox_2")
        self.calculate = QtWidgets.QPushButton(Form)
        self.calculate.setGeometry(QtCore.QRect(60, 430, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.calculate.setFont(font)
        self.calculate.setStyleSheet("QPushButton{\n"
"    color: rgb(85, 85, 127);\n"
"    background-color: rgb(255, 255, 255);\n"
"width:60px;\n"
"height:100px;\n"
"font-size:14px;\n"
"font-weight: bold;\n"
"border:none;\n"
"text-align:center\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(239, 239, 239);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(180, 214, 255);\n"
"}")
        self.calculate.setObjectName("calculate")
        self.clear = QtWidgets.QPushButton(Form)
        self.clear.setGeometry(QtCore.QRect(60, 490, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.clear.setFont(font)
        self.clear.setStyleSheet("QPushButton{\n"
"    color: rgb(85, 85, 127);\n"
"    background-color: rgb(255, 255, 255);\n"
"width:60px;\n"
"height:100px;\n"
"font-size:14px;\n"
"font-weight: bold;\n"
"border:none;\n"
"text-align:center\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(239, 239, 239);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    background-color: rgb(180, 214, 255);\n"
"}")
        self.clear.setObjectName("clear")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(60, 110, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(85, 85, 127);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(60, 160, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_2.setObjectName("label_2")
        self.plojadRavna = QtWidgets.QLabel(Form)
        self.plojadRavna.setGeometry(QtCore.QRect(60, 340, 201, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(10)
        self.plojadRavna.setFont(font)
        self.plojadRavna.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(85, 85, 127);")
        self.plojadRavna.setObjectName("plojadRavna")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(40, 40, 241, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(12)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(85, 85, 127);")
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.checkBoxx3.setText(_translate("Form", "x 3"))
        self.checkBoxPlus100.setText(_translate("Form", "+100"))
        self.checkBox_2.setText(_translate("Form", "/2"))
        self.calculate.setText(_translate("Form", "Вычислить"))
        self.clear.setText(_translate("Form", "Очистить"))
        self.label.setText(_translate("Form", "Ширина"))
        self.label_2.setText(_translate("Form", "Высота"))
        self.plojadRavna.setText(_translate("Form", " Площадь ="))
        self.label_4.setText(_translate("Form", "Площадь параллеограмма"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
