# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sd.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(20, 20, 361, 261))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.vperedButton = QtWidgets.QPushButton(self.page)
        self.vperedButton.setGeometry(QtCore.QRect(270, 220, 75, 23))
        self.vperedButton.setObjectName("vperedButton")
        self.progressBar = QtWidgets.QProgressBar(self.page)
        self.progressBar.setGeometry(QtCore.QRect(20, 70, 118, 23))
        self.progressBar.setProperty("value", 24)
        self.progressBar.setObjectName("progressBar")
        self.lcdNumber = QtWidgets.QLCDNumber(self.page)
        self.lcdNumber.setGeometry(QtCore.QRect(30, 20, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.commandLinkButton = QtWidgets.QCommandLinkButton(self.page)
        self.commandLinkButton.setGeometry(QtCore.QRect(20, 200, 185, 41))
        self.commandLinkButton.setObjectName("commandLinkButton")
        self.buttonBox = QtWidgets.QDialogButtonBox(self.page)
        self.buttonBox.setGeometry(QtCore.QRect(110, 170, 156, 23))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.nazadButton = QtWidgets.QPushButton(self.page_2)
        self.nazadButton.setGeometry(QtCore.QRect(270, 220, 75, 23))
        self.nazadButton.setObjectName("nazadButton")
        self.dial = QtWidgets.QDial(self.page_2)
        self.dial.setGeometry(QtCore.QRect(30, 20, 50, 64))
        self.dial.setObjectName("dial")
        self.horizontalSlider = QtWidgets.QSlider(self.page_2)
        self.horizontalSlider.setGeometry(QtCore.QRect(80, 150, 160, 22))
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.vperedButton.setText(_translate("Form", "Вперед"))
        self.commandLinkButton.setText(_translate("Form", "CommandLinkButton"))
        self.nazadButton.setText(_translate("Form", "Назад"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
