# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'avtoriz_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Avtorization(object):
    def setupUi(self, Avtorization):
        Avtorization.setObjectName("Avtorization")
        Avtorization.resize(322, 524)
        Avtorization.setStyleSheet("\n"
"QObject  {\n"
"    \n"
"    font: 63 11pt \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(86, 86, 86);\n"
"}\n"
"QPushButton {\n"
"background-color: rgb(212, 212, 212);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"   \n"
"    background-color: rgb(100, 102, 115);\n"
"    border-style: inset;\n"
"}\n"
"QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"    selection-background-color: darkgray;\n"
"}\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    lineedit-password-character: 9679;\n"
"}\n"
"")
        self.verticalLayoutWidget = QtWidgets.QWidget(Avtorization)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 241, 161))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit.setText("")
        self.lineEdit.setFrame(True)
        self.lineEdit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit.setReadOnly(False)
        self.lineEdit.setClearButtonEnabled(False)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Avtorization)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(40, 310, 231, 171))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)

        self.retranslateUi(Avtorization)
        QtCore.QMetaObject.connectSlotsByName(Avtorization)

    def retranslateUi(self, Avtorization):
        _translate = QtCore.QCoreApplication.translate
        Avtorization.setWindowTitle(_translate("Avtorization", "Form"))
        self.label.setText(_translate("Avtorization", "Первое поле для ввода"))
        self.lineEdit.setPlaceholderText(_translate("Avtorization", "Введите ваш логин"))
        self.label_2.setText(_translate("Avtorization", "Второе поле для ввода"))
        self.lineEdit_2.setPlaceholderText(_translate("Avtorization", "Введите ваш пароль"))
        self.pushButton.setText(_translate("Avtorization", "Авторизация"))
        self.pushButton_2.setText(_translate("Avtorization", "Выйти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Avtorization = QtWidgets.QWidget()
    ui = Ui_Avtorization()
    ui.setupUi(Avtorization)
    Avtorization.show()
    sys.exit(app.exec_())
