# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wrong_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wrong(object):
    def setupUi(self, Wrong):
        Wrong.setObjectName("Wrong")
        Wrong.resize(241, 168)
        Wrong.setStyleSheet("\n"
"QObject  {    \n"
"    font: 63 11pt \"Yu Gothic UI Semibold\";\n"
"background-color: rgb(86, 86, 86);\n"
"}\n"
"QPushButton {\n"
"background-color: rgb(212, 212, 212);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    border-radius: 10px;\n"
"    border-color: beige;\n"
"    font: bold 14px;\n"
"    min-width: 10em;\n"
"    padding: 6px;\n"
"}\n"
"QPushButton:pressed {\n"
"   \n"
"    background-color: rgb(100, 102, 115);\n"
"    border-style: inset;\n"
"}")
        self.verticalLayoutWidget = QtWidgets.QWidget(Wrong)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 20, 208, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setText("")
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.ok = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.ok.setObjectName("ok")
        self.verticalLayout.addWidget(self.ok)

        self.retranslateUi(Wrong)
        QtCore.QMetaObject.connectSlotsByName(Wrong)

    def retranslateUi(self, Wrong):
        _translate = QtCore.QCoreApplication.translate
        Wrong.setWindowTitle(_translate("Wrong", "Form"))
        self.ok.setText(_translate("Wrong", "ок"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Wrong = QtWidgets.QWidget()
    ui = Ui_Wrong()
    ui.setupUi(Wrong)
    Wrong.show()
    sys.exit(app.exec_())
