# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sd.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(379, 483)
        self.zagolovok = QtWidgets.QLabel(Form)
        self.zagolovok.setGeometry(QtCore.QRect(120, 30, 121, 41))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Semibold")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.zagolovok.setFont(font)
        self.zagolovok.setObjectName("zagolovok")
        self.click_me_button = QtWidgets.QPushButton(Form)
        self.click_me_button.setGeometry(QtCore.QRect(40, 290, 291, 23))
        self.click_me_button.setObjectName("click_me_button")
        self.exit_button = QtWidgets.QPushButton(Form)
        self.exit_button.setGeometry(QtCore.QRect(50, 400, 121, 23))
        self.exit_button.setObjectName("exit_button")
        self.about_programm = QtWidgets.QPushButton(Form)
        self.about_programm.setGeometry(QtCore.QRect(220, 400, 111, 23))
        self.about_programm.setObjectName("about_programm")
        self.input = QtWidgets.QLineEdit(Form)
        self.input.setGeometry(QtCore.QRect(30, 130, 331, 20))
        self.input.setObjectName("input")
        self.add_in_input = QtWidgets.QLabel(Form)
        self.add_in_input.setGeometry(QtCore.QRect(40, 130, 181, 16))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(152, 152, 152))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(152, 152, 152))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        self.add_in_input.setPalette(palette)
        self.add_in_input.setObjectName("add_in_input")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.zagolovok.setText(_translate("Form", "MessageBox"))
        self.click_me_button.setText(_translate("Form", "Нажми!"))
        self.exit_button.setText(_translate("Form", "Выход"))
        self.about_programm.setText(_translate("Form", "О программе"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
