# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zastavka.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Zastavka(object):
    def setupUi(self, Zastavka):
        Zastavka.setObjectName("Zastavka")
        Zastavka.resize(623, 380)
        Zastavka.setStyleSheet("QProgressBar{\n"
"    border: 2px solid grey;\n"
"    border-radius: 5px;\n"
"    text-align: center\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: black;\n"
"    width: 10px;\n"
"    margin: 1px;\n"
"}")
        self.fon = QtWidgets.QLabel(Zastavka)
        self.fon.setGeometry(QtCore.QRect(0, 0, 621, 381))
        self.fon.setText("")
        self.fon.setPixmap(QtGui.QPixmap(":/newPrefix/mishka.jpg"))
        self.fon.setScaledContents(True)
        self.fon.setObjectName("fon")
        self.progressBar = QtWidgets.QProgressBar(Zastavka)
        self.progressBar.setGeometry(QtCore.QRect(10, 320, 601, 51))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.WaitLabel = QtWidgets.QLabel(Zastavka)
        self.WaitLabel.setGeometry(QtCore.QRect(190, 50, 281, 51))
        font = QtGui.QFont()
        font.setFamily("Yu Gothic UI Light")
        font.setPointSize(18)
        self.WaitLabel.setFont(font)
        self.WaitLabel.setText("")
        self.WaitLabel.setObjectName("WaitLabel")
        self.zagruziButton = QtWidgets.QPushButton(Zastavka)
        self.zagruziButton.setGeometry(QtCore.QRect(440, 250, 141, 41))
        self.zagruziButton.setStyleSheet("QPushButton{\n"
"    background-color: rgb(255, 255, 255);\n"
"width:60px;\n"
"height:100px;\n"
"font-size:14px;\n"
"border:none;\n"
"text-align:center\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: rgb(239, 239, 239);\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    \n"
"    background-color: rgb(255, 224, 245);\n"
"}")
        self.zagruziButton.setObjectName("zagruziButton")

        self.retranslateUi(Zastavka)
        QtCore.QMetaObject.connectSlotsByName(Zastavka)

    def retranslateUi(self, Zastavka):
        _translate = QtCore.QCoreApplication.translate
        Zastavka.setWindowTitle(_translate("Zastavka", "Form"))
        self.zagruziButton.setText(_translate("Zastavka", "Загрузить"))
        
from Resource import images


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Zastavka = QtWidgets.QWidget()
    ui = Ui_Zastavka()
    ui.setupUi(Zastavka)
    Zastavka.show()
    sys.exit(app.exec_())
