# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'note.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1020, 635)
        Form.setStyleSheet("QPushButton {\n"
"    background-color: #2B5DD1;\n"
"    color: #FFFFFF;\n"
"    border-style: outset;\n"
"    padding: 2px;\n"
"    font: bold 20px;\n"
"    border-width: 6px;\n"
"    border-radius: 10px;\n"
"    border-color: #2752B8;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: #A52A2A;\n"
"}")
        self.add_button = QtWidgets.QPushButton(Form)
        self.add_button.setGeometry(QtCore.QRect(850, 150, 151, 41))
        self.add_button.setObjectName("add_button")
        self.save_Button = QtWidgets.QPushButton(Form)
        self.save_Button.setGeometry(QtCore.QRect(610, 570, 391, 41))
        self.save_Button.setObjectName("save_Button")
        self.calendarWidget = QtWidgets.QCalendarWidget(Form)
        self.calendarWidget.setGeometry(QtCore.QRect(30, 160, 561, 451))
        self.calendarWidget.setStyleSheet("font: 600 9pt \"Yu Gothic UI Semibold\";")
        self.calendarWidget.setObjectName("calendarWidget")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(0, 0, 1021, 141))
        self.label.setStyleSheet("font-size:24pt;\n"
"background-color: rgb(13, 67, 90);\n"
"color:white;\n"
"border-radius:8px;")
        self.label.setObjectName("label")
        self.taskLineEdit = QtWidgets.QLineEdit(Form)
        self.taskLineEdit.setGeometry(QtCore.QRect(610, 160, 231, 22))
        self.taskLineEdit.setObjectName("taskLineEdit")
        self.taskListWidget = QtWidgets.QListWidget(Form)
        self.taskListWidget.setGeometry(QtCore.QRect(610, 200, 391, 361))
        self.taskListWidget.setObjectName("taskListWidget")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.add_button.setText(_translate("Form", "Add new"))
        self.save_Button.setText(_translate("Form", "Save Changes"))
        self.label.setText(_translate("Form", "                                           Daily Task Planner"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
