# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sd.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(397, 334)
        self.Input1 = QtWidgets.QLineEdit(Form)
        self.Input1.setGeometry(QtCore.QRect(40, 50, 121, 20))
        self.Input1.setObjectName("Input1")
        self.input2 = QtWidgets.QLineEdit(Form)
        self.input2.setGeometry(QtCore.QRect(230, 50, 121, 20))
        self.input2.setObjectName("input2")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(40, 80, 47, 13))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(240, 80, 47, 13))
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 100, 121, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButtonCM1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonCM1.setObjectName("radioButtonCM1")
        self.verticalLayout.addWidget(self.radioButtonCM1)
        self.radioButtonM1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonM1.setObjectName("radioButtonM1")
        self.verticalLayout.addWidget(self.radioButtonM1)
        self.radioButtonKM1 = QtWidgets.QRadioButton(self.verticalLayoutWidget)
        self.radioButtonKM1.setObjectName("radioButtonKM1")
        self.verticalLayout.addWidget(self.radioButtonKM1)
        self.perevesti = QtWidgets.QPushButton(Form)
        self.perevesti.setGeometry(QtCore.QRect(90, 250, 211, 41))
        self.perevesti.setObjectName("perevesti")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(230, 99, 121, 121))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButtonCM2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButtonCM2.setObjectName("radioButtonCM2")
        self.verticalLayout_2.addWidget(self.radioButtonCM2)
        self.radioButtonM2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButtonM2.setObjectName("radioButtonM2")
        self.verticalLayout_2.addWidget(self.radioButtonM2)
        self.radioButtonKM2 = QtWidgets.QRadioButton(self.verticalLayoutWidget_2)
        self.radioButtonKM2.setObjectName("radioButtonKM2")
        self.verticalLayout_2.addWidget(self.radioButtonKM2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Из"))
        self.label_2.setText(_translate("Form", "В"))
        self.radioButtonCM1.setText(_translate("Form", "См"))
        self.radioButtonM1.setText(_translate("Form", "М"))
        self.radioButtonKM1.setText(_translate("Form", "Км"))
        self.perevesti.setText(_translate("Form", "Перевести"))
        self.radioButtonCM2.setText(_translate("Form", "См"))
        self.radioButtonM2.setText(_translate("Form", "М"))
        self.radioButtonKM2.setText(_translate("Form", "Км"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
